### ISSUE TITLE
Obrázok nie je prispôsobený v mobilnej verzii

### ISSUE THREAD

**Issue by ricco386** [microbitsk/microbit.github.io#11]
**Obrázok nie je prispôsobený v mobilnej verzii**
Úvodný obrázok: https://www.microbit.sk/static/img/microbit/26146391212_d21e009360_z.jpg nezobrazuje dobre. Je príliš veľký.

**Ako zreprodukovať**
1. Otvor stránku https://www.microbit.sk/ v mobilnom zariadení
2. Obrázok je veľký

**Očakávané správanie**
Zobrazí sa obrázok primeranej veľkosti

**Ako to vyriešiť**
Spraviť CSS media query na načítanie menšieho obrázky pre nízkom rozlíšení.

**Bonusová úloha**
Spraviť zmenšeniny všetkých obrázkov a optimalizovať pre web

**Comment by mimmon** [comment]
nestačí zmeniť classu? u mňa to funguje bez problémov.
či chcem vylepšiť aj performance, preto to alternatívne rozlíšenie?
